version: '3'
services:
  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8080:80"
    volumes:
      - ./dreams-lab-portal/static/rock-tiles/mbtiles:/data/mbtiles
      - ./dreams-lab-portal/static/rock-tiles/config.json:/data/config.json
    environment:
      - CORS_ORIGIN=*
      - CACHE_SIZE=0
      - CACHE_MAX_AGE=0
    restart: unless-stopped 